

# This file was *autogenerated* from the file división.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
R = PolynomialRing(RR, _sage_const_2 , "xy", order = "lex", names=('x', 'y',)); (x, y,) = R._first_ngens(2)

def div_multinomio(F, f, R = R):
    """
    Implementa el algoritmo de division
    de polinomios multivariados.
    De: Ideals, Varieties, and Algorithms, pag 65
    F es una lista de polinomios, f es el polinomio a dividir
    """
    q = [R(_sage_const_0 ) for _ in range(len(F))]
    r = R(_sage_const_0 )
    p = f

    while p!=R(_sage_const_0 ):
        i=_sage_const_0 
        divisionoccurred = False
        while i<len(F) and not divisionoccurred:

            quo = R.monomial_quotient(p.lt(),F[i].lt(),coeff=True)
            rem = p.lt().reduce(F[i].lt())

            if rem == _sage_const_0 :
                q[i] = q[i]+quo
                p = p - quo*F[i]
                divisionoccurred = True
            else:
                i += _sage_const_1 
        if not divisionoccurred:
            r = r+p.lt()
            p = p-p.lt()

    return q, r


# Ejemplo 1

f = x*y**_sage_const_2 +y
f1 = x*y+_sage_const_1 
f2 = y+_sage_const_1 

# Ejemplo 2

f = x**_sage_const_2 *y+x*y**_sage_const_2 +y**_sage_const_2 
f1 = y**_sage_const_2 -_sage_const_1 
f2 = x*y-_sage_const_1 

F, r = div_multinomio([f1,f2], f)

print(F,r)

print(F[_sage_const_0 ]*f1+F[_sage_const_1 ]*f2 + r)


